[app]
name = "cmdb"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "cmdb"
password = "xxxx"
database = "cmdb"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"